"""Validates synthetic source data generated by generate_training_data.py.

Checks that source positions differ across (mass, ellipticity) parameter groups,
then plots the caustic coverage for two representative parameter combinations.

Run from the `pipeline/` directory.
"""

from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd

from columns import MASS_PARAM_COL, ELLIP_PARAM_COL, SOURCE_COLS

# =============================================================================
# Configuration
# =============================================================================
DATA_FILE = Path("/home/alex/Documents/Grav Lens/data/sources/quad_lens_sources.parquet")

GROUP_COLS = MASS_PARAM_COL + ELLIP_PARAM_COL

FILTER_1_MASS  = 3
FILTER_1_ELLIP = 0.2
FILTER_2_MASS  = 1
FILTER_2_ELLIP = 0.4

# =============================================================================
# Load data
# =============================================================================
df = pd.read_parquet(DATA_FILE)
print(len(df))

# =============================================================================
# Group consistency check
# =============================================================================
groups = df.groupby(GROUP_COLS)
pos_by_group = {
    name: g[SOURCE_COLS].reset_index(drop=True)
    for name, g in groups
}

if not pos_by_group:
    print("No groups found (empty dataframe or missing grouping columns).")
else:
    ref_key = next(iter(pos_by_group))
    ref_df  = pos_by_group[ref_key]

    same_count = sum(1 for v in pos_by_group.values() if v.equals(ref_df))
    total      = len(pos_by_group)
    diff_count = total - same_count

    print(f"Total groups: {total}")
    print(f"Groups exactly the same as reference {ref_key}: {same_count}")
    print(f"Groups different from reference {ref_key}: {diff_count}")

    if diff_count:
        diffs = [k for k, v in pos_by_group.items() if not v.equals(ref_df)]
        print("Example differing groups (up to 20):")
        for d in diffs[:20]:
            print(" ", d)
    else:
        print(ref_key)

# =============================================================================
# Caustic coverage plots
# =============================================================================
df1 = df[(df['Mass Parameter'] == FILTER_1_MASS) & (df['Ellipticity'] == FILTER_1_ELLIP)].copy()
df2 = df[(df['Mass Parameter'] == FILTER_2_MASS) & (df['Ellipticity'] == FILTER_2_ELLIP)].copy()

plt.scatter(df1["Source Dec position"], df1["Source RA position"], s=0.5, label='Source')
plt.grid()
plt.legend()
plt.title(f"Mass={FILTER_1_MASS}, Ellipticity={FILTER_1_ELLIP}")
plt.close()

plt.scatter(df2["Source Dec position"], df2["Source RA position"], s=0.5, label='Source')
plt.grid()
plt.legend()
plt.title(f"Mass={FILTER_2_MASS}, Ellipticity={FILTER_2_ELLIP}")
plt.close()
